services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: stage
      POSTGRES_PASSWORD: stage
      POSTGRES_DB: stage_promo
    ports:
      - "5432:5432"
    volumes:
      - stage_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stage -d stage_promo"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  stage_pg:
