import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { DATA_DIR } from "@/config/env";
import { CANVAS, safeBox, type DialectPack, type Ratio } from "@/domain";

/**
 * Text is rendered with Sharp from SVG using the pack's font (§24.4) — never ffmpeg drawtext,
 * which does not shape Devanagari conjuncts reliably.
 */

export function escXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

/** Greedy line wrap on whitespace to a maximum number of characters per line. */
export function wrapLines(text: string, maxChars: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if (cur && (cur + " " + w).length > maxChars) {
      lines.push(cur);
      cur = w;
    } else cur = cur ? `${cur} ${w}` : w;
  }
  if (cur) lines.push(cur);
  if (lines.length > maxLines) {
    const kept = lines.slice(0, maxLines);
    kept[maxLines - 1] = `${kept[maxLines - 1]}…`;
    return kept;
  }
  return lines;
}

export function captionSize(pack: DialectPack, ratio: Ratio): number {
  return ratio === "9:16" ? pack.typography.caption_size_916 : ratio === "1:1" ? pack.typography.caption_size_11 : pack.typography.caption_size_169;
}

function fontFace(fontPath: string): string {
  const data = fs.readFileSync(fontPath).toString("base64");
  return `@font-face{font-family:'D';src:url('data:font/ttf;base64,${data}') format('truetype');}`;
}

export interface CardSpec {
  w: number;
  h: number;
  text: string;
  fontPath: string;
  fontSize: number;
  lineHeight: number;
  maxLines: number;
  /** semi-transparent backing behind the text (for overlays on footage) */
  backing: boolean;
  align?: "center" | "top";
  color?: string;
}

/** Render a transparent PNG card of exactly w×h with centred, wrapped text. */
export async function renderTextCard(spec: CardSpec): Promise<Buffer> {
  const approxCharW = spec.fontSize * 0.55;
  const maxChars = Math.max(6, Math.floor((spec.w - 2 * Math.round(spec.fontSize * 0.5)) / approxCharW));
  const lines = wrapLines(spec.text, maxChars, spec.maxLines);
  const lh = Math.round(spec.fontSize * spec.lineHeight);
  const blockH = lines.length * lh;
  const top = spec.align === "top" ? Math.round(spec.fontSize * 0.4) : Math.round((spec.h - blockH) / 2);
  const baseY = top + Math.round(spec.fontSize * 0.95);
  const pad = Math.round(spec.fontSize * 0.5);
  const backing = spec.backing
    ? `<rect x="${Math.round(spec.w * 0.02)}" y="${Math.max(0, top - pad)}" width="${Math.round(spec.w * 0.96)}" height="${blockH + 2 * pad}" rx="${Math.round(spec.fontSize * 0.25)}" fill="#000000" fill-opacity="0.62"/>`
    : "";
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${spec.w}" height="${spec.h}">
  <style>${fontFace(spec.fontPath)} text{font-family:'D';font-size:${spec.fontSize}px;fill:${spec.color ?? "#FFFFFF"};font-weight:700}</style>
  ${backing}
  ${lines.map((l, i) => `<text x="${spec.w / 2}" y="${baseY + i * lh}" text-anchor="middle">${escXml(l)}</text>`).join("\n  ")}
</svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

/** Designed CTA background: `/src/data/cta/{dialect}/{ratio}.png`, generated by scripts/make-cta-backgrounds.ts. */
export function ctaBackgroundPath(dialect: string, ratio: Ratio): string | null {
  const p = path.join(DATA_DIR, "cta", dialect, `${ratio.replace(":", "x")}.png`);
  return fs.existsSync(p) ? p : null;
}

/** Fallback background if a designed PNG is missing (still no model involved). */
export async function fallbackCtaBackground(ratio: Ratio): Promise<Buffer> {
  const c = CANVAS[ratio];
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${c.w}" height="${c.h}"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1C1C20"/><stop offset="1" stop-color="#0B0B0D"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

/**
 * CTA text card: title name (large) + CTA line, inside the safe area. Composited by Sharp in the
 * pack's font. The returned card is exactly the safe box size so D8 holds by construction.
 */
export async function renderCtaCard(args: { ratio: Ratio; titleNative: string; ctaText: string; pack: DialectPack; fontPath: string }): Promise<{ png: Buffer; w: number; h: number }> {
  const sb = safeBox(args.ratio);
  const size = captionSize(args.pack, args.ratio);
  const titleSize = Math.round(size * 1.45);
  const lh = args.pack.typography.line_height;
  const titleLines = wrapLines(args.titleNative, Math.max(6, Math.floor(sb.w / (titleSize * 0.55))), 2);
  const ctaLines = wrapLines(args.ctaText, Math.max(6, Math.floor(sb.w / (size * 0.55))), 2);
  const titleLh = Math.round(titleSize * lh);
  const ctaLh = Math.round(size * lh);
  const gap = Math.round(size * 0.8);
  const blockH = titleLines.length * titleLh + gap + ctaLines.length * ctaLh + Math.round(size * 1.6);
  const top = Math.round((sb.h - blockH) / 2);
  const wordmarkY = top + titleLines.length * titleLh + gap + ctaLines.length * ctaLh + Math.round(size * 1.2);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${sb.w}" height="${sb.h}">
  <style>${fontFace(args.fontPath)} .t{font-family:'D';font-size:${titleSize}px;fill:#FFFFFF;font-weight:700} .c{font-family:'D';font-size:${size}px;fill:#E8E8EC;font-weight:700} .m{font-family:'D',sans-serif;font-size:${Math.round(size * 0.9)}px;fill:#3D7EFF;font-weight:700;letter-spacing:${Math.round(size * 0.12)}px}</style>
  ${titleLines.map((l, i) => `<text class="t" x="${sb.w / 2}" y="${top + Math.round(titleSize * 0.95) + i * titleLh}" text-anchor="middle">${escXml(l)}</text>`).join("\n  ")}
  ${ctaLines.map((l, i) => `<text class="c" x="${sb.w / 2}" y="${top + titleLines.length * titleLh + gap + Math.round(size * 0.95) + i * ctaLh}" text-anchor="middle">${escXml(l)}</text>`).join("\n  ")}
  <text class="m" x="${sb.w / 2}" y="${wordmarkY}" text-anchor="middle">STAGE</text>
</svg>`;
  return { png: await sharp(Buffer.from(svg)).png().toBuffer(), w: sb.w, h: sb.h };
}
